Algoritmo "CONTADOR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marina Pinheiro
// Data atual  : 12/04/2022
Var
// Seção de Declarações das variáveis
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

  repita
  escreval (contador)
  contador <- contador + 1
  ate (contador > 10)

Fimalgoritmo