Algoritmo "MULTIPLICACAO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marina Pinheiro
// Data atual  : 12/04/2022
Var
// Seção de Declarações das variáveis
n1 , n2 , result : real



Inicio

// Seção de Comandos, procedimento, funções, operadores, etc...

//------------------------------------------------------------------------+
// Passando valores iniciais para as variáveis
//------------------------------------------------------------------------+

n1 <- 0

n2 <- 0

result <- 0



//------------------------------------------------------------------------+
// Apresentação
//------------------------------------------------------------------------+

escreval ("")

escreval ("Software que realiza a operação multiplicação de números.")

escreval ("")

escreval ("Exibe o cálculo e o resultado desta.")

escreval ("")

escreval ("")



//------------------------------------------------------------------------+
// Entrada de dados
//------------------------------------------------------------------------+

escreva ("01 Número:  ")

leia (n1)

escreval ("")

escreva ("02 Número:  ")

leia (n2)

escreval ("")



//------------------------------------------------------------------------+
// Exibindo CÁLCULO que será efetuado
//------------------------------------------------------------------------+

escreval ("Cálculo: ", n1, " * ", n2)

escreval ("")



//------------------------------------------------------------------------+
// Efetuando CÁLCULOS
//------------------------------------------------------------------------+

result <- n1 * n2



//------------------------------------------------------------------------+
// Saída de dados
//------------------------------------------------------------------------+

escreval("Resultado: ", result)



//------------------------------------------------------------------------+
// Pulando linhas
//------------------------------------------------------------------------+

escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
Fimalgoritmo